"""Operational readiness helpers for Alfred."""

from src.operations.config_registry import (
    ConfigurationRegistry,
    DeploymentProfile,
    OptionalService,
    build_configuration_registry,
)
from src.operations.environment_discovery import (
    AutoConfiguredValue,
    DISCOVERY_PROVIDERS,
    DISCOVERY_TRIGGER_BEFORE_DEPLOYMENT,
    DISCOVERY_TRIGGER_BEFORE_OPERATIONAL_READINESS,
    DISCOVERY_TRIGGER_DAILY,
    DISCOVERY_TRIGGER_MANUAL,
    DISCOVERY_TRIGGER_STARTUP,
    EnvironmentComponent,
    EnvironmentDrift,
    EnvironmentInventory,
    build_doctor_summary,
    build_environment_inventory,
    compare_environment_inventory,
    load_environment_inventory,
    render_detected_environment_yaml,
    render_environment_inventory_markdown,
    write_environment_inventory,
)
from src.operations.doctor import (
    DoctorCheck,
    OperationalReadiness,
    build_operational_readiness,
    render_operational_readiness,
    render_operational_readiness_json,
    write_operational_readiness,
)

__all__ = [
    "ConfigurationRegistry",
    "DeploymentProfile",
    "OptionalService",
    "AutoConfiguredValue",
    "DISCOVERY_PROVIDERS",
    "DISCOVERY_TRIGGER_BEFORE_DEPLOYMENT",
    "DISCOVERY_TRIGGER_BEFORE_OPERATIONAL_READINESS",
    "DISCOVERY_TRIGGER_DAILY",
    "DISCOVERY_TRIGGER_MANUAL",
    "DISCOVERY_TRIGGER_STARTUP",
    "EnvironmentComponent",
    "EnvironmentDrift",
    "EnvironmentInventory",
    "DoctorCheck",
    "OperationalReadiness",
    "build_configuration_registry",
    "build_environment_inventory",
    "build_doctor_summary",
    "build_operational_readiness",
    "compare_environment_inventory",
    "load_environment_inventory",
    "render_detected_environment_yaml",
    "render_environment_inventory_markdown",
    "render_operational_readiness",
    "render_operational_readiness_json",
    "write_environment_inventory",
    "write_operational_readiness",
]
